services:
    belfast_db:
        container_name: belfast_db
        image: postgres:alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file: .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U belfast"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    pgdata: